name: Run tests

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: true
      NODE_CACHE_KEY:
        type: string
        required: true

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Load dependencies from cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: node_modules
          key: ${{ inputs.NODE_CACHE_KEY }}

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Run ${{ matrix.test }} test
        run: npm run ${{ matrix.test }}
