name: Run tests

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: true
      NODE_CACHE_KEY:
        type: string
        required: true

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Load dependencies from cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: node_modules
          key: ${{ inputs.NODE_CACHE_KEY }}

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Run ${{ matrix.test }} test
        run: npm run ${{ matrix.test }}
